#!/usr/bin/env python3
"""
WordPress LLM Connector MCP Server
Compatible with MCP 1.6+ and Pydantic 2.10+

Configuration via environment variables:
    WP_LLM_SITE_URL  - WordPress site URL (e.g., https://example.com)
    WP_LLM_API_KEY   - API key generated by the WP LLM Connector plugin
"""

import json
import os
from typing import Optional

import httpx
from mcp.server.fastmcp import FastMCP

# ── Configuration ─────────────────────────────────────────────────────────────

SITE_URL = os.environ.get("WP_LLM_SITE_URL", "").rstrip("/")
API_KEY  = os.environ.get("WP_LLM_API_KEY", "")
BASE     = "/wp-json/wp-llm-connector/v1"
TIMEOUT  = 30.0
UA       = "WP-LLM-Connector-MCP/2.0"

mcp = FastMCP("wordpress")

# ── Helpers ───────────────────────────────────────────────────────────────────

async def _get(endpoint: str) -> dict:
    if not SITE_URL:
        raise ValueError("WP_LLM_SITE_URL is not set.")
    if not API_KEY:
        raise ValueError("WP_LLM_API_KEY is not set.")
    url     = f"{SITE_URL}{BASE}{endpoint}"
    headers = {"X-WP-LLM-API-Key": API_KEY, "User-Agent": UA, "Accept": "application/json"}
    async with httpx.AsyncClient(timeout=TIMEOUT) as client:
        r = await client.get(url, headers=headers)
        r.raise_for_status()
        return r.json()


def _err(e: Exception) -> str:
    if isinstance(e, ValueError):
        return f"Config error: {e}"
    if isinstance(e, httpx.HTTPStatusError):
        s = e.response.status_code
        msgs = {
            401: "Authentication failed — check WP_LLM_API_KEY.",
            403: "Access denied — connector may be disabled.",
            404: f"Endpoint not found: {e.request.url}",
            429: "Rate limit exceeded — try again later.",
        }
        return msgs.get(s, f"HTTP {s}: {e.response.text[:200]}")
    if isinstance(e, httpx.ConnectError):
        return f"Cannot connect to {SITE_URL}"
    if isinstance(e, httpx.TimeoutException):
        return f"Request timed out after {TIMEOUT}s"
    return f"{type(e).__name__}: {e}"


def _json(data) -> str:
    return json.dumps(data, indent=2, ensure_ascii=False)

# ── Tools ─────────────────────────────────────────────────────────────────────

@mcp.tool()
async def wp_health_check() -> str:
    """Check if the WordPress site and LLM Connector plugin are reachable. No authentication required."""
    try:
        url = f"{SITE_URL}{BASE}/health"
        async with httpx.AsyncClient(timeout=TIMEOUT) as client:
            r = await client.get(url, headers={"User-Agent": UA})
            r.raise_for_status()
        return _json({"status": "connected", "site": SITE_URL, **r.json()})
    except Exception as e:
        return _err(e)


@mcp.tool()
async def wp_get_site_info(format: str = "markdown") -> str:
    """Get basic WordPress site information: name, URL, WP version, PHP version, timezone.
    
    Args:
        format: Output format — 'markdown' (default) or 'json'
    """
    try:
        d = await _get("/site-info")
        if format == "json":
            return _json(d)
        return (
            f"# {d.get('site_name', 'WordPress Site')}\n\n"
            f"- **URL**: {d.get('site_url')}\n"
            f"- **WordPress**: {d.get('wp_version')}\n"
            f"- **PHP**: {d.get('php_version')}\n"
            f"- **Timezone**: {d.get('timezone')}\n"
            f"- **Language**: {d.get('language')}\n"
            f"- **Multisite**: {'Yes' if d.get('is_multisite') else 'No'}\n"
        )
    except Exception as e:
        return _err(e)


@mcp.tool()
async def wp_list_plugins(active_only: bool = False, format: str = "markdown") -> str:
    """List all installed WordPress plugins with version and active status.
    
    Args:
        active_only: If True, only return active plugins
        format: Output format — 'markdown' (default) or 'json'
    """
    try:
        data = await _get("/plugins")
        if active_only:
            data = [p for p in data if p.get("active")]
        if format == "json":
            return _json(data)
        active   = [p for p in data if p.get("active")]
        inactive = [p for p in data if not p.get("active")]
        lines = [f"# Plugins ({len(data)} total, {len(active)} active)\n"]
        if active:
            lines.append("## Active\n")
            for p in sorted(active, key=lambda x: x.get("name", "")):
                lines.append(f"- **{p['name']}** v{p.get('version','?')}")
        if inactive and not active_only:
            lines.append(f"\n## Inactive ({len(inactive)})\n")
            for p in sorted(inactive, key=lambda x: x.get("name", "")):
                lines.append(f"- ~~{p['name']}~~ v{p.get('version','?')}")
        return "\n".join(lines)
    except Exception as e:
        return _err(e)


@mcp.tool()
async def wp_list_themes(format: str = "json") -> str:
    """List all installed WordPress themes with active status.
    
    Args:
        format: Output format — 'json' (default) or 'markdown'
    """
    try:
        data = await _get("/themes")
        if format == "json":
            return _json(data)
        lines = ["# Themes\n"]
        for t in data:
            active = " **(Active)**" if t.get("active") else ""
            lines.append(f"- **{t.get('name','?')}** v{t.get('version','?')}{active} — {t.get('author','?')}")
        return "\n".join(lines)
    except Exception as e:
        return _err(e)


@mcp.tool()
async def wp_get_system_status(format: str = "markdown") -> str:
    """Get detailed WordPress server status: PHP, MySQL, memory, filesystem.
    
    Args:
        format: Output format — 'markdown' (default) or 'json'
    """
    try:
        d = await _get("/system-status")
        if format == "json":
            return _json(d)
        s  = d.get("server", {})
        wp = d.get("wordpress", {})
        db = d.get("database", {})
        fs = d.get("filesystem", {})
        return (
            f"# System Status\n\n"
            f"## Server\n"
            f"- **Software**: {s.get('software')}\n"
            f"- **PHP**: {s.get('php_version')}\n"
            f"- **MySQL**: {s.get('mysql_version')}\n"
            f"- **Memory limit**: {s.get('memory_limit')}\n"
            f"- **Max execution**: {s.get('max_execution_time')}s\n\n"
            f"## WordPress\n"
            f"- **Version**: {wp.get('version')}\n"
            f"- **Debug mode**: {'On' if wp.get('debug_mode') else 'Off'}\n"
            f"- **Memory**: {wp.get('memory_limit')}\n\n"
            f"## Database\n"
            f"- **Tables**: {db.get('tables_count')}\n"
            f"- **Size**: {db.get('database_size')}\n\n"
            f"## Filesystem\n"
            f"- **Uploads writable**: {'✅' if fs.get('uploads_writable') else '❌'}\n"
            f"- **Content writable**: {'✅' if fs.get('content_writable') else '❌'}\n"
        )
    except Exception as e:
        return _err(e)


@mcp.tool()
async def wp_get_user_count() -> str:
    """Get WordPress user statistics broken down by role."""
    try:
        return _json(await _get("/user-count"))
    except Exception as e:
        return _err(e)


@mcp.tool()
async def wp_get_post_stats() -> str:
    """Get WordPress content statistics: post counts by type and status (published, draft, etc)."""
    try:
        return _json(await _get("/post-stats"))
    except Exception as e:
        return _err(e)


@mcp.tool()
async def wp_full_diagnostics() -> str:
    """Run a full diagnostic report on the WordPress site covering all available data."""
    sections = []
    calls = [
        ("/site-info",     "Site Information"),
        ("/system-status", "System Status"),
        ("/plugins",       "Plugins"),
        ("/themes",        "Themes"),
        ("/user-count",    "Users"),
        ("/post-stats",    "Content"),
    ]
    for endpoint, label in calls:
        try:
            data = await _get(endpoint)
            sections.append(f"# {label}\n\n```json\n{_json(data)}\n```")
        except Exception as e:
            sections.append(f"# {label}\n\n⚠️ {_err(e)}")
    return "\n\n---\n\n".join(sections)


# ── Entry point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    mcp.run()